const FEATURES=['sharpness','gradient','edge_density','mean_luminance','dark_ratio','bright_ratio','luma_std','dynamic_range','noise_residual','local_variance','entropy','saturation','clipping_ratio','blockiness'];
const ISSUES=['blur','underexposure','overexposure','noise','corruption','visual_defect'];
const VARIANTS=['clean','blur','underexposure','overexposure','noise','severe','defect','combined'];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}}
function softmax(z){const m=Math.max(...z),e=z.map(v=>Math.exp(v-m)),s=e.reduce((a,b)=>a+b,0)||1;return e.map(v=>v/s)}
function sigmoid(z){return 1/(1+Math.exp(-Math.max(-30,Math.min(30,z))))}
function source(r){const u=r;const v=[.72+.05*(u()-.5),.68+.07*(u()-.5),.18+.06*(u()-.5),.50+.06*(u()-.5),.05+.04*u(),.04+.03*u(),.21+.035*(u()-.5),.74+.07*(u()-.5),.08+.025*u(),.10+.04*u(),.72+.06*(u()-.5),.47+.05*(u()-.5),.02+.025*u(),.08+.05*u()];return Object.fromEntries(FEATURES.map((k,i)=>[k,clamp(v[i])]))}
function generateDataset(seed=42024){const r=rng(seed),data=[];for(let sid=0;sid<160;sid++){const base=source(r);for(let vi=0;vi<8;vi++){const variant=VARIANTS[vi],sev=variant==='clean'?.05:[.3,.6,.9][(sid+vi)%3],x={...base},labels=[];const p=(v,s)=>{if(v==='blur'){x.sharpness-=.25*s;x.gradient-=.20*s;x.edge_density-=.15*s;x.blockiness+=.10*s;labels.push('blur')}else if(v==='underexposure'){x.mean_luminance-=.30*s;x.dark_ratio+=.45*s;x.dynamic_range-=.16*s;labels.push('underexposure')}else if(v==='overexposure'){x.mean_luminance+=.30*s;x.bright_ratio+=.45*s;x.clipping_ratio+=.36*s;x.dynamic_range-=.13*s;labels.push('overexposure')}else if(v==='noise'){x.noise_residual+=.55*s;x.local_variance+=.45*s;x.entropy+=.13*s;x.sharpness-=.08*s;x.edge_density+=.04*s;labels.push('noise')}else if(v==='defect'){x.local_variance+=.55*s;x.noise_residual+=.32*s;x.blockiness+=.52*s;x.edge_density+=.15*s;x.entropy+=.13*s;labels.push('visual_defect')}};
if(variant==='severe'){p('blur',.7*sev);p('noise',.8*sev);p('underexposure',.55*sev);x.clipping_ratio+=.20*sev;x.blockiness+=.22*sev;labels.push('corruption')}else if(variant==='combined'){const opts=['blur','noise','underexposure','overexposure'],a=opts[Math.floor(r()*4)],b=opts[Math.floor(r()*4)];p(a,sev*.85);if(b!==a)p(b,sev*.7);if(sev>.75)labels.push('corruption')}else if(variant!=='clean')p(variant,sev);for(const k of FEATURES)x[k]=clamp(x[k]+(r()-.5)*.012);const quality=variant==='clean'?0:(variant==='severe'||labels.includes('corruption')||(variant==='overexposure'&&sev>.8)?2:1);const issues=Object.fromEntries(ISSUES.map(k=>[k,labels.includes(k)?1:0]));data.push({source_id:sid,variant,severity:sev,features:x,quality,issues});}}return data}
function split(data){return{train:data.filter(d=>d.source_id<112),validation:data.filter(d=>d.source_id>=112&&d.source_id<136),test:data.filter(d=>d.source_id>=136)}}
function fit(data){const X=data.map(d=>FEATURES.map(k=>d.features[k])),mean=FEATURES.map((_,i)=>X.reduce((s,x)=>s+x[i],0)/X.length),std=FEATURES.map((_,i)=>Math.sqrt(X.reduce((s,x)=>s+(x[i]-mean[i])**2,0)/X.length)||1);const Z=data.map(d=>FEATURES.map((k,i)=>(d.features[k]-mean[i])/std[i])),A=Z.map(x=>[1,...x]);const qW=Array.from({length:3},()=>Array(15).fill(0));for(let ep=0;ep<300;ep++){const g=Array.from({length:3},()=>Array(15).fill(0));for(let n=0;n<A.length;n++){const p=softmax(qW.map(w=>w[0]+w.slice(1).reduce((s,a,j)=>s+a*Z[n][j],0)));for(let c=0;c<3;c++){const e=p[c]-(data[n].quality===c?1:0);g[c][0]+=e;for(let j=0;j<14;j++)g[c][j+1]+=e*Z[n][j]}}for(let c=0;c<3;c++)for(let j=0;j<15;j++)qW[c][j]-=.07*(g[c][j]/A.length+.001*qW[c][j])}
const issueWeights={};for(const issue of ISSUES){const w=Array(15).fill(0),y=data.map(d=>d.issues[issue]);for(let ep=0;ep<260;ep++){const g=Array(15).fill(0);for(let n=0;n<A.length;n++){const p=sigmoid(w[0]+w.slice(1).reduce((s,a,j)=>s+a*Z[n][j],0)),e=p-y[n];g[0]+=e;for(let j=0;j<14;j++)g[j+1]+=e*Z[n][j]}for(let j=0;j<15;j++)w[j]-=.07*(g[j]/A.length+.001*w[j])}issueWeights[issue]=w}
return{version:'quality-v2.0',classifier:'multinomial logistic regression + binary issue heads',feature_names:FEATURES,mean,std,quality_weights:qW,issue_weights:issueWeights,trained_at:new Date().toISOString(),training:{seed:42024,source_profiles:160,variants_per_source:8,split:{train_sources:112,validation_sources:24,test_sources:24},examples:{train:data.filter(d=>d.source_id<112).length,validation:data.filter(d=>d.source_id>=112&&d.source_id<136).length,test:data.filter(d=>d.source_id>=136).length}}}}
function predict(model,features){const x=model.feature_names.map((k,i)=>((Number(features[k])||0)-model.mean[i])/(model.std[i]||1));const q=softmax(model.quality_weights.map(w=>w[0]+w.slice(1).reduce((s,a,j)=>s+a*x[j],0)));const issues={};for(const [k,w] of Object.entries(model.issue_weights))issues[k]=sigmoid(w[0]+w.slice(1).reduce((s,a,j)=>s+a*x[j],0));return{quality:q,issues}}
function metrics(model,data){const cm=Array.from({length:3},()=>Array(3).fill(0)),pr=[],ir=Object.fromEntries(ISSUES.map(k=>[k,{tp:0,fp:0,fn:0}])),failures=[];for(const d of data){const p=predict(model,d.features),yp=p.quality.indexOf(Math.max(...p.quality));cm[d.quality][yp]++;pr.push({t:d.quality,p:yp});if(yp!==d.quality||Math.max(...p.quality)<.55){const x=model.feature_names.map((k,i)=>((Number(d.features[k])||0)-model.mean[i])/(model.std[i]||1));const contrib=model.quality_weights[yp].slice(1).map((w,i)=>({feature:model.feature_names[i],contribution:Math.abs(w*x[i])})).sort((a,b)=>b.contribution-a.contribution).slice(0,4).map(v=>({feature:v.feature,contribution:+v.contribution.toFixed(3)}));const sorted=[...p.quality].sort((a,b)=>b-a);failures.push({source_id:d.source_id,variant:d.variant,severity:d.severity,true_label:['ACCEPTABLE','DEGRADED','DEFECTIVE'][d.quality],predicted_label:['ACCEPTABLE','DEGRADED','DEFECTIVE'][yp],confidence:+Math.max(...p.quality).toFixed(3),probabilities:p.quality.map(x=>+x.toFixed(3)),top_contributing_features:contrib,ambiguity_gap:+(sorted[0]-sorted[1]).toFixed(3),reason:sorted[0]-sorted[1]<.08?'Close class scores':d.variant==='combined'?'Combined degradation interaction':'Low-confidence prediction',features:d.features});}for(const k of ISSUES){const y=d.issues[k],h=p.issues[k]>=.5?1:0;if(y&&h)ir[k].tp++;else if(!y&&h)ir[k].fp++;else if(y&&!h)ir[k].fn++}}const rows=cm.map((r,c)=>{const tp=r[c],fp=cm.reduce((s,x)=>s+x[c],0)-tp,fn=r.reduce((s,x)=>s+x,0)-tp;const precision=tp/(tp+fp||1),recall=tp/(tp+fn||1);return{precision,recall,f1:2*precision*recall/(precision+recall||1)}});const acc=pr.filter(x=>x.t===x.p).length/pr.length;const macro=k=>rows.reduce((s,r)=>s+r[k],0)/3;const issue={};for(const k of ISSUES){const a=ir[k],precision=a.tp/(a.tp+a.fp||1),recall=a.tp/(a.tp+a.fn||1);issue[k]={precision,recall,f1:2*precision*recall/(precision+recall||1)}}failures.sort((a,b)=>a.confidence-b.confidence);return{accuracy:acc,macro_precision:macro('precision'),macro_recall:macro('recall'),macro_f1:macro('f1'),examples:data.length,confusion_matrix:cm,issue,failures:failures.slice(0,10)}}
export const DATASET_SPEC={seed:42024,source_profiles:160,variants_per_source:8,variants:VARIANTS,split:'source profiles are assigned to train/validation/test before variants are generated',severity_levels:['LOW','MEDIUM','HIGH']};
export function trainAndEvaluate(){const data=generateDataset();const s=split(data),model=fit(s.train);return{model,validation:metrics(model,s.validation),test:metrics(model,s.test),dataset:{total:data.length,train:s.train.length,validation:s.validation.length,test:s.test.length,class_distribution:Object.fromEntries([0,1,2].map(c=>[c,data.filter(d=>d.quality===c).length])),variants:Object.fromEntries(VARIANTS.map(v=>[v,data.filter(d=>d.variant===v).length]))}}}
export {predict,FEATURES,ISSUES};